### ISSUE TITLE
Stale link generated when combined is true.

### ISSUE THREAD

**Issue by koffeiniker** [alexandre-perrin/mkdocs-pandoc-plugin#2]
In plugin.py about line 110 the indentation is wrong. The modify_html-call must be indented one level further to be part of the else-branch. Otherwise, when combined is true, both links will be injected, one being stale as with combined on the individual page-pdfs do not get generated.

**Comment by alexandre-perrin** [comment]
Thanks for spotting this issue @koffeiniker.

This is now resolved.
